" Settings
set nocompatible " required for Vundle and it is nevertheless a good idea to set
set noswapfile 
set backspace=indent,eol,start " allow backspacing over autoindent, line breaks and the beginning of insert mode
set history=50
set fileformats=unix,dos
set mouse=a " enables mouse support in all modes
set clipboard=unnamed " access X clipboard via the * and + register
set hidden " Allow switching edited buffers without saving
set scrolloff=3 " shows the next or previous 3 lines under or above the cursor
"set listchars=tab:>-,trail:.,eol:$ " characters for tab, trailing spaces and eol when activate 'set list'
set listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮ " characters for tab, trailing spaces and eol when activate 'set list'
set undofile " activates persistent undo
set undodir=~/.vimundo/ " if undofile is activated, a directory is needed where the undofiles are stored
set tags=./tags;
set completeopt=menu,preview,longest
set wildignorecase " completion on files in command mode is now case insensitive
set autoread " if a file outside of the current vim session is modified it can be read in by :checktime, see :help E321
set modelines=0 " don't need modelines and the potential security hazard
set scroll=10
set showmode
set path=$PWD/**
set shell=/bin/bash
set visualbell
set t_Co=256 " activate 256 color support if your terminal supports it and haven't configured to use it

" vim gui stuff
set cursorline " highlight current cursor line
"set cursorcolumn " highlight current cursor column
set showmatch " show matching brackets/parenthesis
set number
set ruler " shows line numbers
set showcmd " show entered command in normal mode
set ttyfast " send more characters for redraws

set wildmenu
set wildmode=longest:full,full " first tab complete only longest common string, second tab complete to first element in list

set wildignore+=*.aux,*.out,*.toc " LaTeX intermediate files
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg " binary images
set wildignore+=*.class " java class files

" searching
set incsearch " find as you type search
set ignorecase " do not search case sensitive
set smartcase " Case sensitive if we type an uppercase
set hlsearch

" tabs -> spaces
set expandtab " tabs will be spaces
set tabstop=4 " one tab is 4 spaces
set shiftwidth=4 " indention will be 4 spaces
set smarttab " backspace over tabs

" filetype
set autoindent
set copyindent " copy the previous indentation on autoindenting
syntax on
filetype plugin on " apply settings based on filetype
filetype indent on " indention for known file extensions
set omnifunc=syntaxcomplete#Complete

" spell checking
set thesaurus+=~/.vim/openthesaurus.txt
set spelllang=de,en

" Custome key mappings
noremap <C-j> :bnext<CR>
noremap <C-k> :bprevious<CR>
noremap <C-h> :tabprevious<CR>
noremap <C-l> :tabNext<CR>

" use the arrow key to move between windows
nnoremap <Left> <C-w>h
nnoremap <Down> <C-w>j
nnoremap <Up> <C-w>k
nnoremap <Right> <C-w>l

" clears the last search pattern to disable highlighting
map <silent> <leader>h :let @/ = ""<CR>
map <silent> <leader>s :setlocal invspell<CR>
map <silent> <leader>r :source ~/.vimrc<CR>
map <leader>p :set invpaste paste?<CR>

" on the qwertz keyboard ctrl-y is a harder to reach then on a qwerty keyboard
noremap <silent> <C-z> <C-y>

function! Run(...)
    let args = ''
    for i in a:000
       let args = args . ' ' . i
    endfor

    if &filetype == "java"
        execute "!java " . args . " " . expand("%:r")
    elseif &filetype == "tex"
        execute "silent !zathura --fork " . args . " " . expand("%:r") . ".pdf >& /dev/null"
    elseif &filetype == "sh"
        execute "!bash "  . args . " " . expand("%")
    elseif &filetype == "python"
        execute "!python " . args . " " . expand ("%")
    elseif &filetype == "html"
        execute "silent! !firefox " . expand("%") . " >& /dev/null"
        execute "redraw!"
    elseif &filetype == "markdown"
        execute "silent! !firefox " . expand("%:r") . ".html >& /dev/null"
        execute "redraw!"
    elseif &filetype == "prolog"
        execute "!swipl " . args . " " . expand ("%")
    else
        echoerr "Error: Run() isn't defined for this filetype."
    endif
endfunction

command! -nargs=* Run call Run(<f-args>)

function! InvertBrackets()
    let bracket = getline(".")[col(".")-1]
    if bracket == "("
        execute "normal!r)"
    elseif bracket == ")"
        execute "normal!r("
    elseif bracket == "}"
        execute "normal!r{"
    elseif bracket == "{"
        execute "normal!r}"
    elseif bracket == "["
        execute "normal!r]"
    elseif bracket == "]"
        execute "normal!r["
    elseif bracket == "<"
        execute "normal!r>"
    elseif bracket == ">"
        execute "normal!r<"
    endif
endfunction

command! InvertBrackets call InvertBrackets()

let $LOCALFILE=expand("~/.vimrc.local")
if filereadable($LOCALFILE)
    source $LOCALFILE
endif
