#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}
HC_BIN="${XDG_CONFIG_HOME:-$HOME/.config/herbstluftwm/bin}"

hc emit_hook reload

hc set default_frame_layout 3
hc set frame_bg_transparent 1
hc set tree_style '╾│ ├╰╼─╮'

# colors
hc set frame_gap 4
hc set frame_border_active_color '#49351D'
hc set frame_border_normal_color '#73532D'
hc set frame_bg_normal_color '#BD9768'
hc set frame_bg_active_color '#BD8541'
hc set frame_border_width 0
hc set window_gap 7
hc set window_border_width 3
hc set window_border_normal_color black
hc set window_border_active_color 'grey'
hc set auto_detect_monitors 1
hc set swap_monitors_to_get_tag 0

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind Mod4-x spawn dmenu_run -i -h 23
hc keybind $Mod-m spawn $HC_BIN/herbstcommander.sh
hc keybind $Mod-Return spawn ${TERMINAL:-xterm}

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space spawn $HC_BIN/layout_change.sh
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Ctrl-h resize left +$RESIZESTEP
hc keybind $Mod-Ctrl-j resize down +$RESIZESTEP
hc keybind $Mod-Ctrl-k resize up +$RESIZESTEP
hc keybind $Mod-Ctrl-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab cycle_monitor
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma use_index -1 --skip-visible

# move focused window through tags
hc keybind $Mod-Shift-period move_index +1
hc keybind $Mod-Shift-comma move_index -1

hc keybind $Mod-Shift-m spawn $HC_BIN/merge_tag.sh

# screen handling
hc keybind $Mod-Ctrl-Up spawn $HC_BIN/monitor_manager.sh up
hc keybind $Mod-Ctrl-Down spawn $HC_BIN/monitor_manager.sh down
hc keybind $Mod-Ctrl-Right spawn $HC_BIN/monitor_manager.sh right
hc keybind $Mod-Ctrl-Left spawn $HC_BIN/monitor_manager.sh left
hc keybind $Mod-Ctrl-Return spawn $HC_BIN/monitor_manager.sh single

hc rename default 1
hc add 2

for key in $(seq 0 8); do
    hc keybind "$Mod-$((key+1))" use_index "$key"
    hc keybind "$Mod-Shift-$((key+1))" move_index "$key"
done

# rules
hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY)' focus=on pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|SPLASH)' manage=off
hc rule class=Plugin-container fullscreen=on focus=on

hc pad 0 23
hc set_layout grid

. ${XDG_CONFIG_HOME:-"$HOME/.config"}/herbstluftwm/autostart.local
