#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc set default_frame_layout 3
hc set frame_bg_transparent 1
hc set tree_style '╾│ ├╰╼─╮'

# colors
hc set frame_gap 4
hc set frame_border_active_color '#49351D'
hc set frame_border_normal_color '#73532D'
hc set frame_bg_normal_color '#BD9768'
hc set frame_bg_active_color '#BD8541'
hc set frame_border_width 0
hc set window_gap 7
hc set window_border_width 3
hc set window_border_normal_color black
hc set window_border_active_color 'grey'
hc set auto_detect_monitors 1

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-x spawn dmenu_run -i -p "Execute:"
hc keybind $Mod-m spawn ${XDG_CONFIG_HOME:-$HOME/.config/herbstluftwm/bin}/herbstcommander.sh
hc keybind $Mod-Return spawn ${TERMINAL:-xterm}

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space spawn ${XDG_CONFIG_HOME:-$HOME/.config/herbstluftwm/bin/}layout_change.sh
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Ctrl-h resize left +$RESIZESTEP
hc keybind $Mod-Ctrl-j resize down +$RESIZESTEP
hc keybind $Mod-Ctrl-k resize up +$RESIZESTEP
hc keybind $Mod-Ctrl-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab cycle_monitor
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# cycle through tags
hc keybind $Mod-period use_index +1
hc keybind $Mod-comma use_index -1

# tags
TAG_NAMES=( {1..2} )
TAG_KEYS=( {1..2} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use "${TAG_NAMES[$i]}"
        hc keybind "$Mod-Shift-$key" move "${TAG_NAMES[$i]}"
    fi
done

# rules
hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY)' focus=on pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|SPLASH)' manage=off
hc rule class=Plugin-container fullscreen=on focus=on

hc pad 0 23
hc set_layout grid

. ${XDG_CONFIG_HOME:-"$HOME/.config"}/herbstluftwm/autostart.local
